### ISSUE TITLE
Error on form submit for forms with multiple recipients and notify

### ISSUE THREAD

**Issue by krazyjakee** [roundhouse/FormBuilder-Craft-CMS#11]
When I include a comma separated list of emails, and check notify the user I get an "Invalid email" error which displays the two emails I added.

The input on the form is simply a single input with "yourEmail" as the id.

**Comment by owldesign** [comment]
Very good find! It should now be fixed, thanks.

**Comment by krazyjakee** [comment]
You're awesome dude.
