### ISSUE TITLE
Need help to make save entry and email notification work

### ISSUE THREAD

**Issue by daituzhang** [roundhouse/FormBuilder-Craft-CMS#12]
Hi, I've installed and put a form template. The form is displayed well, however no submission are saved into entries or sending a submission notification. The post request I can find is a 302 redirect request. Is there any extra steps that I should do to make above work?
Thank you!

**Comment by owldesign** [comment]
Hmm I would double check few things to make sure you set it up correctly. Check these:
1. When you create a form via CMS make sure you check the `"Notify Registrant?"` checkbox. After that make sure the template in fact exists at this path` "formbuilder/email/registrant"`
2. Make sure the email input handle name is `yourEmail` exactly (for the front-end). I am using that handle to notify the submitter. You can either create email field via CMS or use the `sampleForm.html` line `37`

Please check those and let me know if you have any questions.

**Comment by daituzhang** [comment]
Hi I double checked the steps you mentioned a bove
1.
![field-checked](https://cloud.githubusercontent.com/assets/4118473/7432876/b741815e-eff1-11e4-9488-ba429eda6d07.png)
for notification templates, I copied the example ones from the plugin
![notification-templates](https://cloud.githubusercontent.com/assets/4118473/7432881/b9e6731a-eff1-11e4-9262-b3822b6136af.png)

2. I also added the handle to the form template
![form-template](https://cloud.githubusercontent.com/assets/4118473/7432895/ca9faf46-eff1-11e4-96c1-75fee17a92cc.png)

But it still doesn't seem to work.

Thank you for your help!

**Comment by owldesign** [comment]
Ok looks like you have few things wrong. Lets fix it up.

1. When creating the form make sure your paths are exactly the same as in this screenshot.
![screen shot 2015-05-01 at 9 40 39 am](https://cloud.githubusercontent.com/assets/438764/7433451/3db5fc76-efe6-11e4-9865-da143e8a5945.png)

The templates do not live in your crafts template folder (your second screenshot) so you can delete that whole `email` directory. The templates we are using live in the actual plugins directory (see my screenshot)
![screen shot 2015-05-01 at 9 43 32 am](https://cloud.githubusercontent.com/assets/438764/7433482/93068db2-efe6-11e4-9325-f0aa7e4be2c4.png)

2. In your last screenshot you have the field wrong. Looks like you are adding an email address to the `name` and `id`. You need to replace the email with  `yourEmail` value. Just like the screenshot bellow. This basically allows whoever fills out the form to be notified. 
![screen shot 2015-05-01 at 9 48 04 am](https://cloud.githubusercontent.com/assets/438764/7433535/2d00a7b8-efe7-11e4-9a83-9c4b8904be8b.png)

Fix these up first, then we'll see if entries get saved! Let me know if you have any questions.

**Comment by daituzhang** [comment]
Thank you so much for replying!!!
I did exactly as above so I will skip the screenshots
1. the templates path exactly is formbuilder/template/email/default, I've tried with that as well which didn't solve the problem anyway.
2. I did `value:  form.yourEmail is defined ? form.yourEmail : 'daituzhang@gmail.com',`
should be correct this time.
But still didn't get submission.

Thank you!!!

**Comment by owldesign** [comment]
For (2) did you change 
`
name:   "yourEmail",
id"         "yourEmail"
`
Make sure those values actually say `yourEmail` and not your email address.

Also you should probably leave the value default field empty `' '`. 

Try this just drop the following code in place of your field without changing anything, just leave as is.
```
{# Email Address #}
{{forms.textField({
    label:  "Email Address"|t,
    name:   "yourEmail",
    id:     "yourEmail",
    value:  form.yourEmail is defined ? form.yourEmail : '',
})  }}
```

**Comment by daituzhang** [comment]
Hi I copied exactly the same thing. And it didn't work.
And I don't think that's the issue either because that field is just for sending the confirmation emails to the ones who have submitted. But I have issues to receive the notification to my email box as well as on the plugin entry tab.

Thank you for the instruction!!

**Comment by owldesign** [comment]
Hmm I'm not sure whats up.  If you willing to email me zipped up project folder I can test it, but otherwise I'm out of ideas :(

**Comment by daituzhang** [comment]
Hi! Sorry,
Made it work. I see. The "youremail" is required and has to be a valid email. I think the saveEntry might be triggered only after the submission email is sent.
Thank you for all your helping!!!
I may need to see how to make it work without required email.

**Comment by owldesign** [comment]
Great, good luck.
