### ISSUE TITLE
Entries can only show 5 fields at most

### ISSUE THREAD

**Issue by daituzhang** [roundhouse/FormBuilder-Craft-CMS#14]
Sorry to disturb again. It seems the entries can only show the first 5 fields. But all fields will be shown in the submission email.
Is there a way to fix it?

Thank you!

**Comment by owldesign** [comment]
I have set it to only show you few fields for preview. If you click entry id it will give you all the fields.

BUT if you really want to show more you can updated the following code to however many fields you want to show.. (you'll need to change this every time I make update to the plugin though..soo)

Open `models/FormBuilder_EntryModel.php` and on line `54` change the number `4` to however many fields you want to show. If you don't want a limit delete or comment that line out completely.

Let me know if that doesn't work.
Thanks.
