### ISSUE TITLE
Templates fit for a front-end

### ISSUE THREAD

**Issue by krazyjakee** [roundhouse/FormBuilder-Craft-CMS#15]
Copying the back end form templates to the front end has served us all well but leaves a convoluted mess of functionality which leaves little room for creativity as is explained in these issues...

https://github.com/roundhouse/FormBuilder-Craft-CMS/issues/6
https://github.com/roundhouse/FormBuilder-Craft-CMS/issues/7

These issues can be answered by creating a simple template system with the `fields` object here: https://github.com/roundhouse/FormBuilder-Craft-CMS/blob/master/sampleForm.html#L45.

Using custom macros we can generate form elements with full customisation possibilities.
Something like https://github.com/eliteArea/twig_macro (README).

I think this would be a great solution to really enable some fine forms. Let me know your thoughts on this. Maybe you already had something else in mind?

**Comment by owldesign** [comment]
This is interesting. I'll poke around this and see what I can come up with. Looks promising

**Comment by owldesign** [comment]
I have updated the plugin. We now have custom fieldtypes that allow us to write our own input markup.
