### ISSUE TITLE
Preserve Field Values on Error

### ISSUE THREAD

**Issue by jake-pump** [roundhouse/FormBuilder-Craft-CMS#16]
Hey loving the plugin so far, is there a way to preserve the user entered input values (such as a name field), and output them in the input when an error is detected?

For example on my form I have a name and email field which are both required, if I fill out the name field and not the email field, and hit submit it will generate an error for the empty email field, however the value entered into the name field is lost and has to be re-entered.

Thanks in advance.

**Comment by owldesign** [comment]
I won't have time to look into this until this weekend, if you don't figure it out by then, I'll help.

**Comment by owldesign** [comment]
I have updated the plugin. It now comes with validation. You will need to set the fields you want validation on to "required". Checkout documentation here https://github.com/roundhouse/FormBuilder-Craft-CMS#required-fields

That will add HTML5 required attribute to the input field. But I'd suggest you use ajax for form submission, that includes parsleyjs. Better validation with messages. When you make your form you'll have an option to "check" Use Ajax.


Thanks.
