### ISSUE TITLE
Assets field not working properly

### ISSUE THREAD

**Issue by johanhatlehols** [roundhouse/FormBuilder-Craft-CMS#17]
Hi,

first of all; great work on the plugin.

I am not sure if this is an issue or if I'm going about this the wrong way, but I am having problems with the Assets field.

I am creating an application form, and I want my users to be able to upload their CV. So far, the only thing I have done is adding the assets field to the form using the FormBuilder.

Please see attached image for the output I receive on front end / in the code. As you can see, there is no way to actually upload the assets.

![output-frontend](https://cloud.githubusercontent.com/assets/11923309/7811955/630e8002-03ae-11e5-9847-203169012488.png)
![output-code](https://cloud.githubusercontent.com/assets/11923309/7811956/63349666-03ae-11e5-8a48-c9349abf6a43.png)

Could you give me some pointers on what I am doing wrong?

Thanks in advance.

/Johan

**Comment by krazyjakee** [comment]
@johanhatlehols try changing the hidden input (name="curriculumVitae") to a file input type="file" and remove the "Add an asset" button.

**Comment by owldesign** [comment]
I have actually tried to implement craft's asset field but could not get it going because there is a bunch of javascript that the asset field requires. This js is loaded by default on the admin side but not the front-end. I might have to roll out my own custom fieldtype for the file upload. Either way I'll get uploads working within the next push. Hopefully this week sometime.

**Comment by johanhatlehols** [comment]
Hi,

thanks for responding! That's great. Looking forward to it :)

Mvh
Johan Jøsok

**Comment by owldesign** [comment]
I have updated this plugin, but will need more time to work on the upload fieldtype.

**Comment by owldesign** [comment]
I have added file upload field to regular post requests. No ajax support yet, so if your form submits via ajax, this field won't work.

ajax support coming soon.
