### ISSUE TITLE
Plugin Folder Name

### ISSUE THREAD

**Issue by brandoncarroll** [roundhouse/FormBuilder-Craft-CMS#2]
I wasn't able to get Craft to recognize the plugin when the plugin's folder was named 'FormBuilder', as instructed in the documentation here: http://roundhouse.github.io/FormBuilder-Craft-CMS/

Renaming the folder to 'formbuilder' fixed this issue.

**Comment by owldesign** [comment]
Thanks for the catch, updated documentation.
