### ISSUE TITLE
Missing stylesheet in production

### ISSUE THREAD

**Issue by krazyjakee** [roundhouse/FormBuilder-Craft-CMS#21]
> http://www.domain.com/admin/resources/formbuilder/css/formbuilder.css?x=CqXpOFlsZ 

No issues in dev mode, but in production that url throws a 404. Any ideas?

EDIT: Looks like it's unrelated to devmode/production. Ooh! I think it's case sensitive.

**Comment by krazyjakee** [comment]
https://github.com/roundhouse/FormBuilder-Craft-CMS/pull/22

**Comment by owldesign** [comment]
Yes I renamed the file from formBuilder.css  to formbuilder.css but for some reason github keeps renaming it to uppercase B..
