### ISSUE TITLE
Error when saving a form.

### ISSUE THREAD

**Issue by krazyjakee** [roundhouse/FormBuilder-Craft-CMS#23]
I've upgraded from the previous version.

> Internal Server Error
Property "Craft\FormBuilder_FormRecord.ajaxSubmit" is not defined.

The ajax submit checkbox is unticked.

EDIT: Looks to be columns missing. Possibly a bad migration? Or perhaps no migration?

The workaround is to completely uninstall the plugin and re-install the latest version. Of course, you lose the existing forms and entries.

**Comment by owldesign** [comment]
Yeah man, I made so much updates that I needed a fresh database columns. You can manually just add the fields into your database table from the FormRecord file. Update your columns manually and see if that fixes

**Comment by krazyjakee** [comment]
I solved it by exporting the data, re-installing the plugin, then importing the data.

I don't mind if this is closed since there is a workaround. I'll leave it up to you.

**Comment by owldesign** [comment]
I'll close this, but will add a todo for exporting/importing data for future...or just get better at migrations ha
