### ISSUE TITLE
Example code throws an error

### ISSUE THREAD

**Issue by krazyjakee** [roundhouse/FormBuilder-Craft-CMS#24]
I'm in the process of updating existing forms to the new code as written here: http://roundhouse.github.io/FormBuilder-Craft-CMS/

I'm getting this error when I load the page.

> Template Error
Variable "id" does not exist
/home/vagrant/sites/site/craft/plugins/formBuilder/templates/_components/fieldtypes/PlainText/input.html(4)
01 {% import "_includes/forms" as forms %}
02 
03 {% set config = {
04     id: id,
05     label: name,
06     name: name,
07     value: value,
08     class: 'nicetext',
09     instructions: instructions,
10     maxlength: settings.maxLength,
11     required: required,
12     showCharsLeft: true,
13   placeholder: settings.placeholder,
14     rows: settings.initialRows
15 } %}
16

**Comment by owldesign** [comment]
You still stuck on this one? I would make sure all your database columns are set up correctly first. 

You have to make sure to use `| FormBuilder | Plain Text` etc.. fields only. You maybe just using the crafts field types.. I had to create my owl for better control.

![screen shot 2015-06-05 at 9 37 55 am](https://cloud.githubusercontent.com/assets/438764/8010636/a1e709ba-0b66-11e5-884c-a34d959112e3.png)

**Comment by krazyjakee** [comment]
Hadn't spotted that, thank you!
