### ISSUE TITLE
Errors when using checkboxes

### ISSUE THREAD

**Issue by michael-zerovapor** [roundhouse/FormBuilder-Craft-CMS#3]
When I try to use a checkbox field, I get the following error on form submit. **Line 11 is highlighted**. Viewing the form entries in the control panel also gives me an error alert and won't load the entries. I tried just using 1 checkbox option instead of 3 and making the values url-friendly strings in case that made a difference for some reason, but nothing helped.

## Template Error

Array to string conversion

**/Users/mikeytodd/Projects/pocketmaps-craft/craft/plugins/formbuilder/templates/email/default.html(11)**

```
01 {% if form is defined %}
02   <h3>New {{ form.name }} Submission [{{ entry.id }}]</h3>
03 {% endif %}
04 <hr>
05 {% if data is defined %}
06   <table>
07   {% for key, value in data %}
08     {% if value %}
09     <tr>
10       <td><strong>{{ key | addSpace }}: </strong></td>
11       <td>{{ value }}</td>
12     </tr>
13     {% endif %}
14   {% endfor %}
15   </table>
16 {% endif %}
```

**Comment by owldesign** [comment]
I have fixed this in the last commit, let me know if you run into anything else.

Thanks for contributing.

**Comment by michael-zerovapor** [comment]
Thanks you so much! :)
--

Michael Todd
Front-end Developer / Designer
Look-Listen

912 508 7545 Phone
michael.todd@look-listen.com
