### ISSUE TITLE
Version 1.4.2's migration is broken

### ISSUE THREAD

**Issue by thoaionline** [roundhouse/FormBuilder-Craft-CMS#30]
In the following file

https://github.com/roundhouse/FormBuilder-Craft-CMS/blob/1.4.2/migrations/m150619_155820_formbuilder_UpdateEntriesDataColumnType.php

ColumnType::Mixed is a non-existent constant and will break the migration.

**Comment by owldesign** [comment]
I pushed up the fix. Needed to be `ColumnType::Text`, got mixed up with the Craft's record which uses `Mixed`.

Thanks.

**Comment by thoaionline** [comment]
You also need a new tag mate :)

**Comment by owldesign** [comment]
tags updated!
