### ISSUE TITLE
FormBuilder_EntriesController.php

### ISSUE THREAD

**Issue by timroeleveld** [roundhouse/FormBuilder-Craft-CMS#31]
When I move to the entries section I get this errors:

Fatal error: Can't use function return value in write context in /public_html/craft/plugins/formbuilder/controllers/FormBuilder_EntriesController.php on line 75

Fatal error: Interface 'Craft\Iterator' not found in /public_html/craft/app/framework/collections/CListIterator.php on line 21

**Comment by owldesign** [comment]
what php version are you running?

In your `FormBuilder_EntriesController.php`, Replace lines 75-77 with the following.

```
$uploadedFile = array_values($_FILES)[0];
if (isset($uploadedFile)) {
  $filename = $uploadedFile['name'];
  $file = $uploadedFile['tmp_name'];
```

Let me know if that works?

**Comment by timroeleveld** [comment]
I'm running php version 5.3.29

This is the error I get with the replaced code.

Parse error: syntax error, unexpected '[' in /home2/studiooo/public_html/craft/plugins/formbuilder/controllers/FormBuilder_EntriesController.php on line 75

**Comment by owldesign** [comment]
I would personally update php if you can (at least to 5.5) and you wouldn't have this error. Or try this replace old lines with these

```
$allFiles = array_values($_FILES);
$uploadedFile = array_values($allFiles[0]);
  if (isset($uploadedFile)) {
    $filename = $uploadedFile[0];
    $file = $uploadedFile[2];
```

**Comment by timroeleveld** [comment]
Thanks for your quick reply. Got it working on php 5.6 right now!
Right now I got this error when submitting the form:

Bad Request
The request could not be understood by the server due to malformed syntax.

**Comment by owldesign** [comment]
Revert everything back to how we had it before now that you're on 5.6 and see if you still getting that request error. 

```
if (isset(array_values($_FILES)[0])) {
  $filename = array_values($_FILES)[0]['name'];
  $file = array_values($_FILES)[0]['tmp_name'];
```

**Comment by krazyjakee** [comment]
@timroeleveld did you manage to solve this?

**Comment by timroeleveld** [comment]
Yeah this worked. Thanks for your help Jake and Vadim!

2015-07-31 17:36 GMT+02:00 Jake Cattrall <notifications@github.com>:

**Comment by terrysmyth** [comment]
Hey guys, I was following this thread because I have the exact same problem. 

Fatal error: Can't use function return value in write context in /public_html/craft/plugins/formbuilder/controllers/FormBuilder_EntriesController.php on line 75

Im running on php 5.3 (I cannot, as of right now, update it to a newer version.)

I tried the last suggestion (changing lines 75-77):

$allFiles = array_values($_FILES);
$uploadedFile = array_values($allFiles[0]);
  if (isset($uploadedFile)) {
    $filename = $uploadedFile[0];
    $file = $uploadedFile[2];

This did not work. Any ideas or should i really just focus on the php update?

Thanks,

Terry

**Comment by owldesign** [comment]
Use newer version of this plugin, I don't have the time fixing this on the old plugin.

https://github.com/roundhouse/FormBuilder-2-Craft-CMS

**Comment by terrysmyth** [comment]
Thanks for the message. However now im facing this error:

Parse error: syntax error, unexpected '[' in /home/dmrhk2015/public_html/craft/plugins/formbuilder2/controllers/FormBuilder2Controller.php on line 54

**Comment by owldesign** [comment]
If you're using FormBuilder 2 please create new issues in that repo :)

Without testing anything that error looks like a php version error. Basically for `arrays` I use `[ and ]` where older php uses `array()`. You need php 5.4+ for the FormBuilder 2, you should update!

**Comment by Sphamandla** [comment]
Hi I tried to submit a form using formbuilder2 and got this error:

Bad Request
The request could not be understood by the server due to malformed syntax.

Any idea how i can fix this ?
