### ISSUE TITLE
Storage location is hard coded

### ISSUE THREAD

**Issue by krazyjakee** [roundhouse/FormBuilder-Craft-CMS#34]
I notice here the storage location is hard coded: https://github.com/roundhouse/FormBuilder-Craft-CMS/blob/master/controllers/FormBuilder_EntriesController.php#L90

How does that relate to the asset source that is selected in the interface? It seems to only move to the "storage" folder instead of the folder defined in the asset source.

Am I missing something?

**Comment by owldesign** [comment]
I wanted to use Craft's Asset fieldtype, but its too complicated for me. Current upload, allowed filetypes and where the files are being stored is pretty much hardcoded. This is kind of a quick and dirty for now until I can figure out how to reuse the Asset fieldtype

**Comment by m3ndi3** [comment]
So how would we reference these image uploads in our template if we wanted to show our front end submissions? It seems like when I link a url to storage/formbuilder it will give a 404 error.

**Comment by briankalwat** [comment]
@owldesign so how does this even work if your craft folder is above web root? When I click to view assets it gives me a 404 because http://my-domain/craft/.... doesn't exist...

**Comment by owldesign** [comment]
@briankalwat Im in the process of releasing Craft 2 which fixes uploads. It will give you more control where to save files, etc. I'd suggest waiting for the new plugin and using that instead, I plan to stop supporting this one after it's released... You can follow the repo here for updates..

You can actually pull that repo down and start using it..I am pretty much done and just trying to get documentation written. I'd suggest you give it a try...check the new sampleForm.twig file (everything is different)

https://github.com/roundhouse/FormBuilder-2-Craft-CMS
