### ISSUE TITLE
Create New Field url is hardcoded

### ISSUE THREAD

**Issue by maketimetodesign** [roundhouse/FormBuilder-Craft-CMS#35]
Not started using it properly yet, but looks like a great plugin, thanks! I just spotted one thing as I have a custom cpTrigger.

Line #48 in fieldlayoutdesigner.html should be:

<a href="{{ url('settings/fields') }}" class="create-field">Create New Field</a>

Thanks again, 
Tom!

**Comment by owldesign** [comment]
Fixed, thanks!

**Comment by maketimetodesign** [comment]
Pleasure! Cheers.
