### ISSUE TITLE
Renaming problems

### ISSUE THREAD

**Issue by m3ndi3** [roundhouse/FormBuilder-Craft-CMS#36]
Hello! I would very much like this to be solves asap! I renamed my folder to "FormBuilder" and put it in my Craft plugins folder, but nothing shows up in the plugins install page. I renamed the folder to "formbuilder" and it showed up fine in the install page. I set up all my forms and plugged in the sample code, but now I got errors on "could not find template file"... so I dug in the code and found in variables, where the template files should be and changed "formBuilder/templates" to "formbuilder/templates" but another error popped up, and I'm just lost. Looking in the code, it looks like things are using formbuilder/ and formBuilder and FormBuilder... Please help!

**Comment by krazyjakee** [comment]
Hey @m3ndi3 

Check out https://github.com/roundhouse/FormBuilder-Craft-CMS/blob/master/variables/FormBuilderVariable.php#L74

I had this issue and fixing the case on line 74 solved it for me.

**Comment by m3ndi3** [comment]
Thanks, yah this solved the template problem but then I got "The filter "inspect" does not exist".. Do you have any ideas where I can fix this error?

**Comment by m3ndi3** [comment]
Also there are references to   formbuilder/css/ and formbuilder/js but that doesn't seem correct to me, because the correct reference would be formbuilder/resources/css formbuilder/resources/js . Everything just seems kinda topsy turvy...

**Comment by krazyjakee** [comment]
You'll need to install the inspector plugin listed on the main plugin directory

**Comment by m3ndi3** [comment]
Thank you that worked!
