### ISSUE TITLE
Override template for inputs

### ISSUE THREAD

**Issue by timkelty** [roundhouse/FormBuilder-Craft-CMS#42]
I want to use my own templates to output my input/label html.
Is there a planned way to do this?

**Comment by timkelty** [comment]
Figured out this is mostly possible like so:
```
    {% for tab in tabs %}
      <div>
        {% set fields = tab.getFields() %}

        {% for field in fields %}
          {% set field = field.getField() %}
            <div>
              <label for="field-{{ field.id }}">{{ field.name }}</label>
              <input
                class=""
                type="text"
                id="field-{{ field.id }}"
                name="{{ field.handle }}"
                value="{{ craft.session.hasFlash('error') ? craft.request.getPost(field.handle) : '' }}"
                placeholder=""
                {% if field.required %}required{% endif %}
              >
              <div>{{ field.instructions }}</div>
          </div>
        {% endfor %}
      </div>
    {% endfor %}
```

However, `field.required` isn't properly set.

**Comment by owldesign** [comment]
I made this plugin to avoid writing markup like that in the template files. Also craft doesn't give you the option to set filed as `required` from the field maker. Only way to do that is to use the field designer, see screenshot. ![screen shot 2015-09-01 at 10 16 04 am](https://cloud.githubusercontent.com/assets/438764/9611139/e59f2702-5092-11e5-93b1-b011f905ce7c.png)

You can update templates here `templates/_includes/forms` if you want, but It will deff get overwritten if you update the plugin. Adding custom markup isn't on the list of features but I might add something like this when Craft 3 comes out.

**Comment by timkelty** [comment]
Thanks for the update.

Maybe the easiest way is to just optionally be able to pass a template folder to override `templates/_includes/forms`. That way one could copy that folder to be outside the plugin and hack away as needed.

**Comment by owldesign** [comment]
Great idea, I like this route better. I'll see what I can do.

**Comment by marcushouse** [comment]
I would recommend passing a template folder just to check for any existing override templates. This way, if someone just wants to overwrite a small few templates, FormBuilder would fist check if a matching template file is found in the specified override structure, otherwise fall back to the original template in the plugin.

**Comment by owldesign** [comment]
I am working on FormBuilder 2 that will have template overwriting features, if you guys need that you'll want to use that plugin because I won't be adding it to this one.  Working hard to get it done!

you can follow here https://github.com/roundhouse/FormBuilder-2-Craft-CMS
