### ISSUE TITLE
FormBuilder only works when user is logged in (admin min my case)

### ISSUE THREAD

**Issue by danielparas** [roundhouse/FormBuilder-Craft-CMS#45]
Hi I've noticed that form builder only works if the user is logged in due to the call to `/admin/actions/formBuilder/entries/saveFormEntry` which causes a redirect to `/admin/login`

(Using AJAX option)

Is there a way around this please? Since form created must be usable by non-logged in users also.

Thanks
Daniel

**Comment by danielparas** [comment]
Modified line 12 - under `formbuilder/resources/js/formbuilder-form.js` to `/actions/` instead of `/admin/actions/`

Is there a reason why `/admin/` was included?

**Comment by owldesign** [comment]
That was an error, good find! I have updated the code now, thanks.
