### ISSUE TITLE
nl2br

### ISSUE THREAD

**Issue by marcushouse** [roundhouse/FormBuilder-Craft-CMS#46]
A few cases where line breaks are not shown from text areas.

In the following files
plugins\FormBuilder\templates\entries\_view.html
plugins\FormBuilder\templates\email\default.html
plugins\FormBuilder\templates\email\registrant.html

this line
<td>{{ value }}</td>

should be 

<td>{{ value|nl2br }}</td>

Then line breaks will show up in the emails and the entries screen.

**Comment by owldesign** [comment]
Thanks for this tip, updated.
