### ISSUE TITLE
Validation not fully working - Server side that was just added

### ISSUE THREAD

**Issue by nevsie** [roundhouse/FormBuilder-Craft-CMS#47]
Hi,
Not looked in too much depth or at the code yet - i will.

At the moment, it only triggers validation if the field is required. 
So for example i have a number field, not required, but i entered "aaa". It was not validated. Made it required and then it was validated and failed as it was not a number.

If i find anything before you i will let you know. N

**Comment by nevsie** [comment]
I just condenses your number case down to one if - as that was the only one at fault. It was checking for required, and if required then checking for number. combined them:

        case "FormBuilder_Number":
            $number = craft()->request->getPost($field->handle);
        	if ($field->required && !ctype_digit($number)) {
	      			$errorMessage[] = $field->name . ' cannot be blank and needs to contain only numbers.';
        	}

line 164ish - services/FormBuilder_EntriesService.php

**Comment by owldesign** [comment]
I updated the validation a little different. In your code if the field is not required and is blank it will return invalid. I also added specific validation messages. 

Thanks!
