### ISSUE TITLE
HTML5 Required attribute

### ISSUE THREAD

**Issue by krazyjakee** [roundhouse/FormBuilder-Craft-CMS#6]
Doesn't seem to be a way to pass the "required" attribute to the input field.

I've fished deep but it looks to be a limitation of craft.

Any further insight?

**Comment by owldesign** [comment]
Yeah I've spent so much time trying to figure that one out and the closes I've seen something happen if you sent the field to "Make Required" it'll add "required" class to the label only..
![screen shot 2015-03-26 at 9 04 52 am](https://cloud.githubusercontent.com/assets/438764/6850581/30249308-d397-11e4-8a3f-9eac5216206e.png)

![screen shot 2015-03-26 at 9 05 51 am](https://cloud.githubusercontent.com/assets/438764/6850596/57db5012-d397-11e4-85c1-96c5a04235b8.png)

I should come back to this in couple of weeks and maybe try to figure a way to add that "required" string to the actual input field as well..its been a while

**Comment by krazyjakee** [comment]
Thanks very much mate!

Quick notes: https://github.com/roundhouse/FormBuilder-Craft-CMS/blob/master/sampleForm.html#L32

References: https://github.com/pixelandtonic/Craft-Release/blob/master/app/templates/_includes/field.html#L14

For a plainText field, it references: https://github.com/pixelandtonic/Craft-Release/blob/master/app/fieldtypes/PlainTextFieldType.php#L70-L77

References: https://github.com/pixelandtonic/Craft-Release/blob/master/app/templates/_components/fieldtypes/PlainText/input.html#L17

References: https://github.com/pixelandtonic/Craft-Release/blob/master/app/templates/_includes/forms.html#L15

FINALLY we arrive at: https://github.com/pixelandtonic/Craft-Release/blob/master/app/templates/_includes/forms/text.html

By this stage, any hope of passing a variable through this web of insanity is lost.

Hope this helps :)

**Comment by owldesign** [comment]
I am implementing the required html5 filed in next push.

**Comment by owldesign** [comment]
Included in the latest push.

Thanks.
