### ISSUE TITLE
Error with sampleForm.html

### ISSUE THREAD

**Issue by mccombs** [roundhouse/FormBuilder-Craft-CMS#8]
The block 

{% for field in fields %}
    {% include "_includes/field" with {
      field: craft.fields.getFieldById(field.fieldId),
      required: field.required,
    } only %}
  {% endfor %}

Returns the following error

A hash key must be followed by a colon (:). Unexpected token "punctuation" of value "}" ("punctuation" expected with value ":")

**Comment by owldesign** [comment]
Hi, are you sure the error is coming from that block? Does it say which line of that block? Unfortunately this doesn't give me much info to troubleshoot.

**Comment by mccombs** [comment]
It pointed to the } only %} line.

I was following these instructions step by step: http://roundhouse.github.io/FormBuilder-Craft-CMS/

**Comment by owldesign** [comment]
Hmm, yeah I'm not exactly sure what the error is. It seems to be working just fine on my end and for few people using this plugin. I wonder if it's something outside the plugin that might be causing the error.

**Comment by mccombs** [comment]
Ya I don't have any idea either. I'll dive in further next week and let you know if I find anything.

**Comment by krazyjakee** [comment]
Have you updated craft? I have noticed some strange data after running the update migrations. It's possible this bug is now resolved.

**Comment by owldesign** [comment]
im closing this one down
