### ISSUE TITLE
Set "To Email" to field value

### ISSUE THREAD

**Issue by krazyjakee** [roundhouse/FormBuilder-Craft-CMS#9]
I need a form to send an email to the user who fills out the form. There's an email field, is there a way to use that as the "to" email?

**Comment by krazyjakee** [comment]
I made a commit to try to add this functionality but I get an error when I try to save a form in the back end.
Here is the commit: https://github.com/krazyjakee/FormBuilder-Craft-CMS/commit/cf1fe3b9c8743df5840ce94073abc72cb3817189

Here is the error:
```
Property "Craft\FormBuilder_FormRecord.toEmailField" is not defined.

/craft/app/framework/db/ar/CActiveRecord.php(162)

150      * PHP setter magic method.
151      * This method is overridden so that AR attributes can be accessed like properties.
152      * @param string $name property name
153      * @param mixed $value property value
154      */
155     public function __set($name,$value)
156     {
157         if($this->setAttribute($name,$value)===false)
158         {
159             if(isset($this->getMetaData()->relations[$name]))
160                 $this->_related[$name]=$value;
161             else
162                 parent::__set($name,$value);
163         }
164     }
165 
166     /**
167      * Checks if a property value is null.
168      * This method overrides the parent implementation by checking
169      * if the named attribute is null or not.
170      * @param string $name the property name or the event name
171      * @return boolean whether the property value is null
172      */
173     public function __isset($name)
174     {
```

**Comment by owldesign** [comment]
You know I already had a branch for notifyRegistrant. I have now merged it into master branch.

Basically when you create/edit form in the admin you now have a checkbox to notify submitter. You also have a new template in the ```templates/email/registrant.html```. In order for this to work you will need to create a field and have the handle be ```yourEmail``` (you're trying to do toEmail, but I'm already using that handle). Is this what you trying to achieve?

**Comment by krazyjakee** [comment]
I've cloned the master, overwritten the original version but I see no new checkbox.

**Comment by krazyjakee** [comment]
Yeah, I'm definitely not seeing a new checkbox anywhere in the admin interface.

**Comment by krazyjakee** [comment]
Looks like you are having the same problem as my original post.
When you save with the new form you get:

```
Internal Server Error
Property "Craft\FormBuilder_FormRecord.notifyRegistrant" is not defined.
```

**Comment by roundhousedev** [comment]
I think you'll need to uninstall the plugin and install it again.

**Comment by krazyjakee** [comment]
Oh dear, I will lose all my forms. Is there a workaround?

**Comment by roundhousedev** [comment]
Let me see if we can just migrate the database. Basically you just need couple of new columns in your database table. Are you comfortable updating database manually, 

Also are you creating all your fields using craft fields? If you uninstall plugin the fields should stay. You'll just have to create form again and drag all the craft's fields back in via the Field Layout Designer.

 You'll lose forms and entries.

**Comment by krazyjakee** [comment]
This worked for me. If anyone else is comfortable editing the database directly, this should work. Remember to back up.

```sql
ALTER TABLE `your_database`.`craft_formbuilder_forms` 
ADD COLUMN `notifyRegistrant` VARCHAR(255) NULL AFTER `subject`,
ADD COLUMN `notificationTemplatePathRegistrant` VARCHAR(255) NULL AFTER `notifyRegistrant`;
```

**Comment by owldesign** [comment]
Great thanks, I updated plugin version and created 2 migrations to add the columns. Now if someone has the plugin installed previously they will be prompted to updated the database. 

Thanks for contributing @krazyjakee !
